id = "vale"
name = "Vale Language Server"
description = "Zed extension adding Vale spell checking and style checking."
version = "0.0.2"
schema_version = 1
authors = ["Jan van den Berg <koozz@linux.com>"]
repository = "https://github.com/koozz/zed-vale"

[language_servers.vale]
name = "Vale Language Server"
language = "Markdown"
